name: mysql
services:
  mysql-db:
    image: mysql:9.5.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql-internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - mysql-internal
      - traefik-proxy
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_URL}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.middlewares.phpmyadmin-secure.redirectscheme.scheme=https
      - traefik.http.routers.phpmyadmin.entrypoints=web
      - traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-secure@docker
      - traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_URL}`)
      - traefik.http.routers.phpmyadmin-secure.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-secure.rule=Host(`${PHPMYADMIN_URL}`)
      - traefik.http.routers.phpmyadmin-secure.tls=true
      - traefik.http.routers.phpmyadmin-secure.tls.certresolver=le
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

networks:
  mysql-internal:
    name: mysql-internal
    internal: true
  traefik-proxy:
    name: traefik-proxy
    external: true