name: postgres
services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgsql-internal
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    networks:
      - pgsql-internal
      - traefik-proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.middlewares.pgadmin-secure.redirectscheme.scheme=https
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.routers.pgadmin.middlewares=pgadmin-secure@docker
      - traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_URL}`)
      - traefik.http.routers.pgadmin-secure.entrypoints=websecure
      - traefik.http.routers.pgadmin-secure.rule=Host(`${PGADMIN_URL}`)
      - traefik.http.routers.pgadmin-secure.tls=true
      - traefik.http.routers.pgadmin-secure.tls.certresolver=le
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

networks:
  pgsql-internal:
    name: pgsql-internal
    internal: true
  traefik-proxy:
    name: traefik-proxy
    external: true