services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    restart: unless-stopped
    networks:
      traefik-proxy:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.portainer-secure.redirectscheme.scheme=https
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.middlewares=portainer-secure@docker
      - traefik.http.routers.portainer.rule=Host(`portainer.example-domain.ru`) # example-domain.ru поменять на свой домен, который привязан к серверу 
      - traefik.http.routers.portainer-secure.entrypoints=websecure
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.example-domain.ru`) # example-domain.ru поменять на свой домен, который привязан к серверу 
      - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.tls.certresolver=le
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true